// <auto-generated />
using System;
using IMCControlAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IMCControlAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231221221650_v3")]
    partial class v3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("IMCControlAPI.Models.IMCOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Max")
                        .HasColumnType("REAL");

                    b.Property<double>("Min")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("IMCOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#DAD82A",
                            Description = "Peso inferior al normal",
                            Max = 18.399999999999999,
                            Min = 0.0
                        },
                        new
                        {
                            Id = 2,
                            Color = "#24BD21",
                            Description = "Peso normal",
                            Max = 24.899999999999999,
                            Min = 18.5
                        },
                        new
                        {
                            Id = 3,
                            Color = "#CB740B",
                            Description = "Peso superior al normal",
                            Max = 29.899999999999999,
                            Min = 25.0
                        },
                        new
                        {
                            Id = 4,
                            Color = "#D50C0C",
                            Description = "Obesidad",
                            Max = 99.0,
                            Min = 30.0
                        });
                });

            modelBuilder.Entity("IMCControlAPI.Models.IMCUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<double>("Imc")
                        .HasColumnType("REAL");

                    b.Property<string>("ImcColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImcDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimesTamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("IMCUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
